# Generated by Django 3.2.15 on 2022-09-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='slug',
            field=models.SlugField(default=1234, unique=True),
            preserve_default=False,
        ),
    ]
